/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://ynh55hlajzeczcvmxfwnb2dlmm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kvn426avgzd7ni3smzcleloboi",
    "aws_cognito_identity_pool_id": "us-east-2:d42a2340-525d-42d4-a94f-63483fdaa260",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_vMmn3vsFw",
    "aws_user_pools_web_client_id": "1aqsonne22i4hrbvv2e6bots14",
    "oauth": {
        "domain": "sheer91ee9a1e-91ee9a1e-staging.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4200/auth-login/,https://main.dxlci0dzp0dy7.amplifyapp.com/auth-login/",
        "redirectSignOut": "http://localhost:4200/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_login_mechanisms": [
        "EMAIL",
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    }
};


export default awsmobile;
